baseURL: https://demonotary.netlify.app/
languageCode: en-us
title: Notary v2
theme: Universal

paginate: 10

menu:
  main:
    - name: Docs
      url: /docs/
      weight: 1
    - name: Blogs
      url: /blogs/
      weight: 2
    - name: Community
      url: /community/
      weight: 3
    - name: Roadmap
      url: /roadmap/
      weight: 4
    - name: Github
      url: https://github.com/notaryproject/notaryproject.dev
      weight: 5
    - name: Twitter
      url: https://twitter.com/NotaryProject
      weight: 6

# menu.topbar:
#   - weight: 1
#     name: Github
#     url: https://github.com/notaryproject/notaryproject.dev
#     pre: "<i class='fa fa-2x fa-github'></i>"

#   - weight: 2
#     name: Twitter
#     url: https://github.com/notaryproject/notaryproject.dev
#     pre: "<i class='fa fa-2x fa-github'></i>"

highlight:
  codeFences: true

params:
  viewMorePostLink: "/blogs/"
  author: "DevCows"
  defaultDescription: Site ads asdf adsf asdf
  style: "default"
  about_us: "<p>The Notary Project is aiming to provide enterprise-grade solutions and cross-industry standards for securing software supply chain</p>"
  copyright: "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."
  disabled_logo: false
  logo_text: Notary
  logo: "img/notaryLogo.png"
  logo_small: "img/notaryLogo.png"
  widgets:
    categories: true
    tags: true
    search: true
  carouselCustomers:
    items: 6
    auto_play: false
    slide_speed: 2000
    pagination_speed: 1000
  carouselTestimonials:
    items: 4
    auto_play: false
    slide_speed: 2000
    pagination_speed: 1000
  carouselHomepage:
    enable: true
    auto_play: true
    slide_speed: 2000
    pagination_speed: 1000
  features:
    enable: true
    cols: 3
  testimonials:
    enable: true
    title: "Testimonials"
    subtitle: "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."
  see_more:
    enable: true
    icon: "far fa-file-alt"
    title: "Do you want to see more from us?"
    subtitle: "We have blogs and documentation to help you around Notary. Do check them out"
    link_url: "/blogs"
    link_text: "Check out blogs"
  recent_posts:
    enable: true
    title: "From our blog"
    subtitle: "The Notary Project is happy to announce the completion of its fuzzing security audit. The audit was carried out by Ada Logics and is part of an initiative by the CNCF to bring fuzzing to the CNCF landscape. The audit spanned several months in late 2022 and early 2023 and resulted in 20 fuzzers written for 3 Notary sub-projects and 2 issues being identified and addressed including a critical security fix."
    hide_summary: false
  footer:
    recent_posts:
    enable: true
  taxonomies:
    category: "categories"
    tag: "tags"
    author: "authors"

params.carousel:
    enable: true

outputFormats:
  - name: HTML
    mediaType: text/html
    isHTML: true
    rel: canonical
  - name: RSS
    mediaType: application/rss+xml
    isHTML: false
    rel: alternate
    permalinkable: false

disableKinds:
  - taxonomyTerm
  - taxonomy
  - page


    

homeInfoParams:
  Title: Notary Project
  Content: this is content

params.topbar:
  enable: true
  text: |
    <p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
    <p class="hidden-md hidden-lg">
      <a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
    </p>






# menu.main:
#     name       : "All Pages"
#     identifier : "menu.allpages"
#     url        : "/blogs/"
#     weight     : 4

# [[menu.main]]
#     name       = "Home"
#     identifier = "section.ap-home"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 1

# [[menu.main]]
#     name       = "Portfolio"
#     identifier = "section.ap-portfolio"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 2

# [[menu.main]]
#     name       = "Shop"
#     identifier = "section.ap-shop"
#     url        = ""
#     weight     = 1
#     parent     = "menu.allpages"
#     post       = 3

# [[menu.main]]
#     name       = "Blog"
#     identifier = "section.ap-blog"
#     url        = ""
#     weight     = 3
#     parent     = "menu.allpages"
#     post       = 4

# [[menu.main]]
#     name       = "Blog Listing Big"
#     url        = "/blog/"
#     weight     = 1
#     parent     = "section.ap-blog"



params.widgets :
    search: true
    categories: true
    tags: true

params.carouselHomepage:
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

params.features:
    enable: true
    cols: 4

params.see_more:
    enable: true
    icon: "far fa-file-alt"
    title: "Do you want to see more?"
    subtitle: "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url: "http://your-site.com/more"
    link_text: "Check other homepages"


summaryLength: 70

params.recent_posts:
    enable: true
    title: From our blog
    subtitle: Pellen
    hide_summary: false

    
params.footerrecent_posts:
    enable = true

params.testimonials:
    enable = true
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

params.clients:
    enable = true
    title = "Our Partners"
    subtitle = "We have proudly collaborated with the following companies."

